### ISSUE TITLE
trying using the conda method

### ISSUE THREAD

**Issue by UnixJunkie** [aspuru-guzik-group/chemical_vae#37]
```
python -m chemvae.train_vae
/usr/local/anaconda3/envs/chemvae/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/anaconda3/envs/chemvae/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/anaconda3/envs/chemvae/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/anaconda3/envs/chemvae/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/anaconda3/envs/chemvae/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/anaconda3/envs/chemvae/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using Theano backend.
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/chemvae/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/anaconda3/envs/chemvae/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/berenger/src/chemical_vae/chemvae/train_vae.py", line 30, in <module>
    from .models import encoder_model, load_encoder
  File "/home/berenger/src/chemical_vae/chemvae/models.py", line 10, in <module>
    from .tgru_k2_gpu import TerminalGRU
  File "/home/berenger/src/chemical_vae/chemvae/tgru_k2_gpu.py", line 73, in <module>
    raise NotImplemented("Backend not implemented")
TypeError: 'NotImplementedType' object is not callable

```

**Comment by ndharms** [comment]
I got a similar error when running this on a Linux machine. However, the code works perfectly on a Mac. There is probably an error with the environment.

**Comment by ghost** [comment]
I replaced NotImplemented with NotImplementedError and it worked fine. (on Windows-10)

**Comment by UnixJunkie** [comment]
please send a PR with the fix if you have one
