### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by leanhug** [aspuru-guzik-group/chemical_vae#4]
I am using Anaconda Python 3.6 with latest Keras and other libraries. When I run
python -m chemvae.train_vae
It complains:
Traceback (most recent call last):
  File "Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "chemical_vae\chemvae\train_vae.py", line 399, in <module>
    main_no_prop(params)
  File "chemical_vae\chemvae\train_vae.py", line 229, in main_no_prop
    AE_only_model, encoder, decoder, kl_loss_var = load_models(params)
  File "chemical_vae\chemvae\train_vae.py", line 161, in load_models
    decoder = decoder_model(params)
  File "chemical_vae\chemvae\models.py", line 137, in decoder_model
    implementation=params['terminal_GRU_implementation'])([x_dec, true_seq_in])
  File "chemical_vae\chemvae\tgru_k2_gpu.py", line 86, in __init__
    self.units = units
AttributeError: can't set attribute

I tried https://github.com/keras-team/keras/issues/7736
And changed the related lines to:
        try:
            self.units = units
        except AttributeError:
            self._units = units
        try:
            self.recurrent_dropout = min(1., max(0., recurrent_dropout))
        except AttributeError:
            self._recurrent_dropout = min(1., max(0., recurrent_dropout))

Then it complains:
ValueError: Layer decoder_tgru expects 3 inputs, but it received 2 input tensors. Input received: [<tf.Tensor 'decoder_gru2_2/transpose_1:0' shape=(?, ?, 488) dtype=float32>, <tf.Tensor 'decoder_true_seq_input_2:0' shape=(?, 120, 35) dtype=float32>]

Please help...

**Comment by jnwei** [comment]
Hi, This library is only supported on Keras versions between 1.0 and 2.0.7.
Perhaps you are running a newer version of Keras?

**Comment by leonhug** [comment]
Thank you!

I created a virtual environment and installed Keras 2.0.7 and made it work.

There is one minor thing to fix. Keras will still complain 
  File "Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 323, in variable
    v.constraint = constraint
AttributeError: can't set attribute

To fix it, replace v.constraint = constraint with:
    try:
        v.constraint = constraint
    except AttributeError:
        v._constraint = constraint

**Comment by jnwei** [comment]
Great, thanks for sharing the fix!

**Comment by KekeZy** [comment]
I modified it according to the method described above, but still the same mistake.
And both lines are reporting a same error. My keras is 2.0.7

  File "anaconda3/envs/chemvae/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 324, in variable
    v.constraint = constraint
AttributeError: can't set attribute
During handling of the above exception, another exception occurred:
  File "anaconda3/envs/chemvae/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 326, in variable
    v.constraint = constraint
AttributeError: can't set attribute
